name: Wake Up Streamlit App

on:
  schedule:
    # Menjalankan setiap 1 jam
    - cron: '0 */1 * * *'

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app to keep it awake
        run: curl -s "https://medical-assistant-project-glend.streamlit.app" > /dev/null
